name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  dateJob:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        run: |
            echo date
  DirectorConent:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory Content
        run: |
            echo ls



